using System;
namespace BlazorCrud.Cliente.Services
{
	public class Informacion
	{
		public Informacion()
		{

			//ESTA CARPETA SERVICES ES LO QUE SERIA NUESTRO CONTROLLER
			//ACA VAMOS A CREAR LAS CLASES DE INTERFAZ QUE TIENEN LOS MÉTDOS
			//TAMBIEN VAMOS A CREAR LAS CLASES QUE DEFINEN LOS MÉTOODOS
			//LA IDEA ES QUE ESTA CAPA SE COMUNIQUE CON LA CAPA SHARED QUE SE COMUNICA CON LA CAPA SERVER
			//DE ESTA FORMA PODEMOS LLEVAR AL CLIENTE LA INFORMACION DE LA BASE DE DATOS Y VICEVERZA


		}
	}
}

